#!/bin/bash

COST_PINEAPPLE=50
COST_BANANA=4
COST_WATERMELON=23
COST_BASKET=1

QUANTITY_PINEAPPLE=1
QUANTITY_BANANA=2
QUANTITY_WATERMELON=3

TOTAL_PINEAPPLE=$(($COST_PINEAPPLE * $QUANTITY_PINEAPPLE))
TOTAL_BANANA=$(($COST_BANANA * $QUANTITY_BANANA))
TOTAL_WATERMELON=$(($COST_WATERMELON * $QUANTITY_WATERMELON))

TOTAL=$(($TOTAL_PINEAPPLE + $TOTAL_BANANA + $TOTAL_WATERMELON + $COST_BASKET))

echo "Total Cost is $TOTAL"